version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
      time: "04:30"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "04:30"
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
      time: "04:30"

  - package-ecosystem: pip
    directory: /tests
    schedule:
      interval: daily
      time: "04:30"
