version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3"
    rust: "1.64"
python:
  install:
    - requirements: requirements-docs.txt
    - method: pip
      path: .
mkdocs:
  configuration: mkdocs.yml
