[package]
name = "pyromark"
version = "0.1.4"
edition = "2021"
license = "MIT"
include = [
    "/pyromark",
    "/src",
    "/Cargo.lock",
    "/Cargo.toml",
    "/LICENSE",
    "/pyproject.toml",
    "/README.md",
]

[lib]
name = "_pyromark"
crate-type = ["cdylib"]

[dependencies]
pulldown-cmark = { version = "0.9.3", default-features = false, features = [
    "simd",
] }
pyo3 = "0.19.0"

[profile.release]
strip = true
lto = "fat"
codegen-units = 1
